version: "3"
services:
  manager:
    container_name: manager
    build:
      context: .
      dockerfile: Dockerfile.manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./benchmark:/benchmark
      - ./manager_logs:/manager_logs
      - ./logs:/logs

    env_file:
      - container-config.env

